Repository 100-hours-a-week/11-ellu-chatbot-ai, pull requests merged in 2025-06, with the labels that each got.

#1 feat: add issue template
  .github/.DS_Store
  .github/ISSUE_TEMPLATE/1-✨feature.md
  .github/ISSUE_TEMPLATE/2-🐛fix.md
  .github/ISSUE_TEMPLATE/3-♻️refactor.md
  .github/ISSUE_TEMPLATE/4-🧪 mainteance_release.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#3 feat: OpenAI model 설정 (#2)
  .gitignore
  model/chat_llm.py
  requirements.txt
Labels: feat

#5 4 feature 챗봇 graph 노드 설정 및 빌더 구성
  model/chat_graph.py
  model/chat_node.py
  model/state.py
Labels: feat

#7 feat: 챗봇 응답별 chain 구현 (#6)
  model/chat_chains.py
Labels: feat

#9 refactor: model, core 폴더구조 변경 (#8)
  core/chat_chains.py
  core/chat_graph.py
  core/chat_node.py
  core/state.py
Labels: refactor

#13 feat: json output parser 구현 (#10)
  model/json_parsed.py
Labels: feat

#17 feat: 사용자 히스토리 및 챗봇 응답 흐름 관리 (#15)
  services/conversation.py
Labels: feat

#21 feat: 챗봇 유저 히스토리 저장 (#14)
  core/chat_history.py
Labels: feat

#23 20 feature 챗봇 스트리밍 api 구현
  app/chat_router.py
  schemas/chat_schema.py
  server.py
Labels: feat

#26 24 refactor code 구조 개선
  app/chat_controller.py
  app/chat_router.py
  core/chat_graph.py
  core/chat_history.py
  core/chat_node.py
  services/conversation.py
  services/streaming.py
Labels: feat

#32 fix: 재응답시 slot 추출 및 병합 수정 (#31)
  core/chat_graph.py
  core/chat_node.py
  services/conversation.py
Labels: fix

#34 refactor: 일정 생성 시작 로딩 문구 수정 (#33)
  services/conversation.py
  services/streaming.py
Labels: refactor

#36 fix: langchain_tavily 패키지 설치 및 클래스명 수정 (#35)
  core/chat_node.py
  requirements.txt
Labels: fix

#38 feature: 응답 개선을 위한 프롬프팅 수정 (#37)
  model/prompt_template.py
Labels: feat

#40 fix: 일정 생성 완료 스트리밍 응답 done = True로 수정 (#39)
  services/streaming.py
Labels: fix

#44 refactor: 일정 생성 완료 시 slot 초기화 (#43)
  core/chat_node.py
Labels: refactor

#47 feature: other 카테고리에 따른 노드 분기 및 체인 추가 (#46)
  core/chat_chains.py
  core/chat_graph.py
  core/chat_node.py
  model/prompt_template.py
  services/streaming.py
Labels: refactor

#49 48 refactor 프롬프팅 개선 및 노드 구조 리팩토링
  core/chat_graph.py
  core/chat_node.py
  model/prompt_template.py
Labels: refactor

#51 fix: preview 삭제 (#50)
  services/conversation.py
  services/streaming.py
Labels: fix

#55 fix: user_id str타입으로 수정 (#54)
  core/database.py
Labels: fix

#57 56 refactor 스트리밍 방식 개선
  core/chat_node.py
  services/conversation.py
  services/streaming.py
Labels: refactor

#60 59 feature 모호한 응답 일정 추천과 관련된 기능
  core/chat_chains.py
  core/chat_graph.py
  core/chat_node.py
  core/state.py
  model/chat_llm.py
  model/prompt_template.py
Labels: feat

#64 refactor: o4-mini 모델 변경 (#63)
  model/chat_llm.py
Labels: refactor
